#:schema node_modules/wrangler/config-schema.json

compatibility_date = "2025-04-06"
name = "test"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "<db_id>"
