#:schema ../../node_modules/wrangler/config-schema.json

compatibility_date = "2025-04-06"
name = "api-dev"

[observability]
enabled = true

[[d1_databases]]
binding = "DB_MBTI"
database_name = "mbti"
database_id = "6d83dd95-5306-467f-b7c8-65b8f09a8400"
migrations_dir = "../../database/mbti/migrations"
